### ISSUE TITLE
Card form

### ISSUE THREAD

**Issue by lcwalther** [lcwalther/learning-app#1]

**Comment by lcwalther** [comment]
_As a user
I want to have a card form
so that I can create new cards_

### Acceptance criteria
- [ ] Has title, content and tags
- [ ] title and content are text
- [ ] tags is an optional list of text
- [ ] it can only be sent, if content and title is filled out
- [ ] after being sent, the form is cleared

### Design/Wireframe/Scribble is attached

### Tasks

- [ ] Create Form component
- [ ] Add styling
- [ ] Add component to docz
- [ ] Create Form component
